### ISSUE TITLE
too long tooltip content breaks the layout on safari

### ISSUE THREAD

**Issue by deebov** [radix-ui/website#136]
### Current Behavior

https://user-images.githubusercontent.com/28673719/114871265-68775280-9df9-11eb-9fcc-db301c533805.mov

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Browser          |    safari     |14.0.2|

**Comment by peduarte** [comment]
Fixed in #132 
![image](https://user-images.githubusercontent.com/372831/114871921-1682fc80-9dfa-11eb-82a9-b99539d94848.png)
