### ISSUE TITLE
Tooltip arrow issue with rounded corners

### ISSUE THREAD

**Issue by dokuniev** [radix-ui/website#170]
## Bug report

Noticed that if the tooltip arrow in on the sides, it gets disconnected from the frame when the frame has rounded corners

### Expected behavior

Tooltip should look seamless when the arrow is on the sides. Would expect to be able to offset the position too a little so that the arrow is a little indented and not flush with the frame sides

### Reproducible example

The issue can be observed in your own docs:
![image](https://user-images.githubusercontent.com/33609/122042882-8d535c00-cd8f-11eb-8c5c-28fc6231388c.png)

### Suggested solution

Provide an offset for tooltip arrow when placed on the sides.

**Comment by benoitgrelard** [comment]
Hey @dokuniev, the `Arrow` part has an `offset` prop specifically for that.
I'll close the issue, but feel free to reopen if I missed something.

**Comment by dokuniev** [comment]
ooops! thanks @benoitgrelard
