### ISSUE TITLE
Pages sometimes load without styles for a split second

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/website#189]
I know we've been aware of this for some time but wanted to get it written down. 

It seems we're depending on @modulz/design-system here so we're on a really old version of stitches. I'm guessing that might have something to do with it. 

It would be good to upgrade to @radix-ui/design-system if possible.

**Comment by peduarte** [comment]
@jjenzz hmm, the DS is already using the latest version of Stitches. How often are you seeing this?

**Comment by jjenzz** [comment]
@peduarte yes the @radix-ui/design-system is using the latest version but we're using @modulz/design-system for the website which is still using stitches canary.

**Comment by peduarte** [comment]
What is `@radix-ui/design-system`? There's no [such package](https://www.npmjs.com/package/@radix-ui/design-system)

Stitches `0.2.0` is available from `@modulz/design-system@0.3.0` 

But that also come up lots of breaking changes. Colors, API, components, etc. 

This is all happening in this PR: https://github.com/radix-ui/website/pull/160

**Comment by jjenzz** [comment]
I know I’ve got the rona but please don’t make me feel insane 😩😅 you committed to that repo 14 minutes ago: github.com/radix-ui/design-system

I assumed that’s what we needed because the package.json there has the latest stitches and the @modulz/design-system repo has been archived.

**Comment by jjenzz** [comment]
I know I've got the 'rona but please don't make me feel insane 😩😅 you committed to that repo 25 minutes ago https://github.com/radix-ui/design-system

I assumed that's the one we need as the package.json there has the latest stitches and this repo is using [@modulz/design-system](https://github.com/modulz/design-system) which depends on canary and has been archived.

![image](https://user-images.githubusercontent.com/175330/122234995-39429780-ceb5-11eb-905b-8b17023f2285.png)

**Comment by jjenzz** [comment]
Oh i see the confusion here, we have a repo with a mismatching package name. Well that's hella confusing.

In that case I don't know what's causing the bug but the report still stands. I get a real noticeable flash of unstyled content in the docs.

**Comment by peduarte** [comment]
Oh 🤣 yeah, I see why it's confusing. We haven't renamed the package name yet - on purpose. 

Let's leave this on, it will be solved when the PR is merged 👍

**Comment by benoitgrelard** [comment]
This has been resolved.
