### ISSUE TITLE
Low contrast text on Tab example in dark mode

### ISSUE THREAD

**Issue by ElianCordoba** [radix-ui/website#191]
## Bug report

[Link](https://radix-ui.com/primitives/docs/components/tabs#basic-example)

<img width="502" alt="Screen Shot 2021-06-17 at 12 05 31" src="https://user-images.githubusercontent.com/34920585/122424050-c98be580-cf64-11eb-97c0-e7884b8d4644.png">

### Your environment

Chrome 91 on MacOS 11.4

**Comment by peduarte** [comment]
Thanks! We'll address this when we update the DS 🚀

**Comment by benoitgrelard** [comment]
That's been addressed with new demos.
