### ISSUE TITLE
 anchor scroll not offsetting correctly

### ISSUE THREAD

**Issue by Deep-Codes** [radix-ui/website#207]
### Current Behavior

The anchor scroll hash is getting cut off.

![radix](https://user-images.githubusercontent.com/61158210/124860159-d1243480-dfce-11eb-8008-8e6246348f29.gif)

### Expected behavior

It shouldn't overlap on the navbar 

### Reproducible example

Visit https://www.radix-ui.com/docs/primitives/components/hover-card#anatomy

### Suggested solution

I tried git clone and fixing this because of some module errors not able to run it.

A fix can be making `scrollMargin ` to be 40.  

https://github.com/radix-ui/website/blob/0da76e6b68282fc34ea87f6c868f3b3b033e0541/lib/scrollToUrlHash.ts#L8

**Comment by benoitgrelard** [comment]
Hey @Deep-Codes, we are currently reworking the docs and have already fixed this issue so I will close it if that's ok?
