### ISSUE TITLE
Polymorphic example has a type error with v0.0.13

### ISSUE THREAD

**Issue by tu4mo** [radix-ui/website#220]
### Reproducible example

https://codesandbox.io/s/rough-morning-n75t0?file=/src/App.tsx

**Comment by andy-hook** [comment]
Hi @tu4mo the sandbox doesn't seem to reflect the title, would you mind updating it to reflect the issue?

Thanks!

**Comment by jjenzz** [comment]
We may have to update the docs to revert to the old recommendation of casting: https://codesandbox.io/s/laughing-kapitsa-98rqk?file=/src/App.tsx

**Comment by andy-hook** [comment]
> Well, that was embarrassing 😩. I updated the repro.

Thanks for that 👍  We've updated the docs to reflect the latest changes.
