### ISSUE TITLE
Document the available `data-*` attrs as part of the API reference for primitives

### ISSUE THREAD

**Issue by Blitz2145** [radix-ui/website#224]
## Documentation

I recently ran into some breakage when upgrading radix dropdown, which would've been more obvious had I seen `&[data-state="open"]` as being a new data attr that I needed to handle in order to setup the animations in stitches. See context in discord here: https://discord.com/channels/752614004387610674/803656831704629298/874377300806893578

### Relevant Radix Component(s)

All radix components should document that data attrs that are part of their public API.

**Comment by andy-hook** [comment]
Some additional thoughts https://github.com/radix-ui/primitives/discussions/1387#discussion-4065712

**Comment by bukinoshita** [comment]
Done on https://github.com/radix-ui/website/pull/407
