### ISSUE TITLE
Tweak Dialog example on homepage

### ISSUE THREAD

**Issue by jjenzz** [radix-ui/website#282]
I thought the `Dialog` example on the radix-ui.com homepage was an `AlertDialog` because it has an OK button… Thoughts on updating the example to avoid confusion between the two component types?

**Comment by benoitgrelard** [comment]
On the frontpage demo you mean right?
I got caught out by the exact same thing when I looked at it the first time.
The demos we have in the actual docs are more recognisable I think.

**Comment by jjenzz** [comment]
Yep 🙂  and yeah, I agree the demos in the docs are clearer.
