### ISSUE TITLE
Website: Horizontal scrolling on home page does not work with Chrome

### ISSUE THREAD

**Issue by jepfp** [radix-ui/website#283]
### Current Behavior

On the home page, I am not able to show the next primitive components by clicking on the arrow right button (also the button "arrow left" does not work).
However: I can scroll with my trackpad.

### Expected behavior

Clicking on the arrow should scroll right / left.

### Your environment

- Windows 10
- Chrome Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by benoitgrelard** [comment]
Do you mean using arrow keys?
If so I can't reproduce your issue as I seem to be able to focus and navigate the demos.

**Comment by jepfp** [comment]
No, I mean by clicking on the buttons, which "show" me, that there are more demos on the right.
Using arrow keys by the way does not work for me either.

**Comment by benoitgrelard** [comment]
Would you be able to screen record what you see? I'm struggling to understand what you mean.

**Comment by jepfp** [comment]
Yes, you can find the video here: https://files.fm/u/zuxvvp2bk

**Comment by vladmoroz** [comment]
Weird, I can't seem to reproduce the issue with the same setup. The arrow buttons work for me. Does anyone else experience this?

**Comment by jjenzz** [comment]
Works fine for me too on macOS Catalina:

![image](https://user-images.githubusercontent.com/175330/143230933-d7fdd7a5-e094-461a-8368-2a816c117c34.png)

@jepfp What operating system are you on?

**Comment by benoitgrelard** [comment]
Works for me too, he mentioned Windows 10 I think.
I've tried it in crossbrowsertesting.com with the exact details and it seems to work fine:

https://user-images.githubusercontent.com/1539897/143234856-0db7ca1f-5cf1-4d64-9ed4-c405f503c401.mov

So perhaps it is an extension or something that's breaking it.

**Comment by jepfp** [comment]
Yes, Windows 10.

I did another video:
- all extensions disabled (and browser restarted)
- interestingly:
  - sometimes I can click and it scrolls, sometimes it doesn't.
  - scrolling a bit with the trackpad and then clicking again on the button sometimes solves the issue --> it looks like, the offset amount (how much I already scrolled) matters. 
- I have a windows computer with a touch screen. So you can see me first using the mouse and later using the touch screen
- I think the window size matters. With a bigger window (e. g. disabled chrome dev tools) I never was able to scroll by clicking on the button.

video: https://files.fm/u/s2qp5tq3j

**Comment by vladmoroz** [comment]
@jepfp this issue should be fixed, please let me know if it works as expected now. Thanks for raising the issue and providing the details 🙏

**Comment by jepfp** [comment]
It works as I would expect. Thanks a lot!
