### ISSUE TITLE
Accessibility overview broken link

### ISSUE THREAD

**Issue by bengeorge** [radix-ui/website#284]
### Current Behavior

https://www.radix-ui.com/docs/primitives/overview/introduction#accessible

Click `accessibility` and it takes you here https://www.radix-ui.com/docs/primitives/overview/docs/primitives/overview/accessibility

Page is a 404

### Expected behavior

I assume the link should be to https://www.radix-ui.com/docs/primitives/overview/accessibility ?

### Reproducible example

n/a

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

**Comment by peduarte** [comment]
Thanks, want to PR a fix in?

**Comment by bengeorge** [comment]
Looks like its covered now, but next time I will. Wasn't sure if you guys wanted external contributors or not.
