### ISSUE TITLE
Component documentation should map more easily to vanilla CSS

### ISSUE THREAD

**Issue by fergusmeiklejohn** [radix-ui/website#291]
## Documentation
Radix component documentation is excellent but has one major drawback IMO, which is that it uses Stitches in a way which encourages abstractions which make the documentation harder to understand. Developers who want to use Radix have to understand Stitches to see how to use the component. Stitches is great but ideally these two technologies should be separated, we don't want to confine Radix to Stitches users, when the library is excellent and has the potential to be used by everyone.

One suggestion from the Discord is to use the core Stitches API which maps more closely to CSS: https://discord.com/channels/752614004387610674/803656831704629298/917373575953018880 

My own experience was that it was difficult to figure out how to get it to work, what the options are, etc.

The way I work with documentation: I like to copy an example into my codebase, change it to fit (eg I'm working on a Tailwind project and a Sass project at the moment) and play around with it to see how it works and what I'll need for my project. The current Radix documentation makes that a bit difficult to do.

**Comment by fergusmeiklejohn** [comment]
some overlap with this issue: https://github.com/radix-ui/website/issues/214

**Comment by peduarte** [comment]
Noted. Thank you <3

**Comment by benoitgrelard** [comment]
Closing in favour of #500
