### ISSUE TITLE
Toggle Group and Tooltip are missing the package size

### ISSUE THREAD

**Issue by adrianmg** [radix-ui/website#319]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/589285/147620655-71329a5a-369f-4f9f-a0ae-f99916a53e4a.png">

<img width="965" alt="image" src="https://user-images.githubusercontent.com/589285/147620943-ae6f9154-9373-4331-bd21-ae182c08dd5a.png">

**Comment by benoitgrelard** [comment]
Yeah we're aware of that. There are issues with the bundlephobia API randomly failing sometimes, so we don't get the size reported at build time…

**Comment by benoitgrelard** [comment]
That's been resolved.
