### ISSUE TITLE
Blurred font in dialog

### ISSUE THREAD

**Issue by alexalannunes** [radix-ui/website#383]
### Current Behavior
In the Dialog component when has a `box-shadow` the content stay with blurred font

![image](https://user-images.githubusercontent.com/16847836/166522624-dcea9bb1-d52e-4501-89c3-8bdb1ba0d7c9.png)

### Expected behavior
The content font shoud be sharp!

![image](https://user-images.githubusercontent.com/16847836/166523017-69b6ccbe-4f67-4f3b-80aa-e32369f58c33.png)

### Reproducible example

[CodeSandbox Template](https://codesandbox.io/s/2r30e)
https://codesandbox.io/s/dialog-demo-blurred-ohgoxt?file=/App.js

**Comment by benoitgrelard** [comment]
This is usually due to transforms, and only visible on non-retina screens.
There are other ways to center the content too, you can nest the content inside the overlay and use flex or grid to center it.

**Comment by jjenzz** [comment]
> There are other ways to center the content too, you can nest the content inside the overlay and use flex or grid to center it.

perhaps the docs website should do this so the examples aren't blurry?
