### ISSUE TITLE
Add examples for styling Primitives with Styled Components

### ISSUE THREAD

**Issue by sidneifjr** [radix-ui/website#427]
I'm using Styled Components for my personal project and I intend to enforce it as my main tool for styling, even though Stitches does have its merits. However, since the few examples available in the docs only use Stitches, I end up having to maintain both. This addition would offer better versatility for a wider range of development stacks.

**Comment by benoitgrelard** [comment]
We're actually leaning towards vanilla CSS examples rather in the long term.
At the moment though, I'm curious why you feel the need for styled-components examples seeing that the stitches API is pretty much the same. Is it not clear how you would go about styling things with styled-components?

**Comment by donsn** [comment]
> I'm using Styled Components for my personal project and I intend to enforce it as my main tool for styling, even though Stitches does have its merits. However, since the few examples available in the docs only use Stitches, I end up having to maintain both. This addition would offer better versatility for a wider range of development stacks.

@sidneifjr I'm using styled-components too and their syntax is similar to stitches

An example

![image (1)](https://user-images.githubusercontent.com/31552644/225563798-422fee39-4587-4cf0-901b-814e546cb3fd.png)


Then use as 

![image (2)](https://user-images.githubusercontent.com/31552644/225564723-7af9a0e1-b455-4d49-a515-af7e11d3bfc1.png)
