### ISSUE TITLE
Components latency on radix-ui.com

### ISSUE THREAD

**Issue by inwardmovement** [radix-ui/website#449]
## Bug report

There is a latency on radix-ui.com, but not in codesandbox.io.
To reproduce, just compare the dropdown menu between radix-ui.com and the codesandbox example:

![radix-latency](https://user-images.githubusercontent.com/9438102/180636455-d4c26a2e-dfa2-448f-82a5-11f363cfe10c.gif)

## Your environment

Chrome 103.0.5060.134 (64 bits)
Windows 10 21H1 (19043.1826)
(also tested on Chromebook, and with Firefox, same latency)

**Comment by andy-hook** [comment]
I'm unable to reproduce on MacOS or virtualised windows. I'll leave this open for now pending time in the future to investigate further.

**Comment by inwardmovement** [comment]
I noticed there is not latency on the homepage with the "Options" dropdown example.

What are the differences between this dropdown and the one on the Dropdown Menu page, that could cause this difference in latency?

**Comment by andy-hook** [comment]
> What are the differences between this dropdown and the one on the Dropdown Menu page, that could cause this difference in latency?

Hard to say without looking into it further, are you seeing the same in any of your projects?

**Comment by inwardmovement** [comment]
I'm not yet using Radix in a project, I'm considering using it and I spotted this 300ms latency while openning the dropdown menu on the dedicated doc page, on at least 2 different browsers and computers.

**Comment by benoitgrelard** [comment]
I can reproduce it on the website only by turning on CPU throttling x6.
The difference would be the size of the tree/general page layout and impact of a style recalculation.

You can see a couple of large style recalc:

<img width="708" alt="CleanShot 2022-08-01 at 14 49 16@2x" src="https://user-images.githubusercontent.com/1539897/182151583-dd1458ae-9378-4d08-99a3-cb44d9f09034.png">

You can probably largely ignore this as it's more dependent to the page you will end up having, possibly being able to use css containment, as the style recalc/reflows are more than likely unavoidable from our side.
