### ISSUE TITLE
Consider being more precise in terms of what the `orientation` prop does (ie. no visual changes).

### ISSUE THREAD

**Issue by petegriffith** [radix-ui/website#463]
### Current Behavior

The orientation prop has no effect on `ToggleGroup`. No matter what, the ToggleGroup has a horizontal orientation.

### Expected behavior

Similar to the Slider, `orientation` ought to change the ToggleGroup's orientation; otherwise it should be removed as an option

### Reproducible example

**Note** The following link comes directly from the ToggleGroup [docs](https://www.radix-ui.com/docs/primitives/components/toggle-group). I am also seeing this issue when running locally.

[CodeSandbox Template](https://codesandbox.io/s/kvb8uo?module=App.js&file=/App.js)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |     @radix-ui/react-toggle-group   |     1.0.0    |
| React            | n/a     |     18.0.0    |
| Browser          |  Chrome     |     105.0.5195.52    |
| Assistive tech   |         |         |
| Node             | n/a     |     16.15.0    |
| npm/yarn         |     pnpm    |  6.32.13       |
| Operating System |    macOS     |     Monterey 12.5.1     |

**Comment by Ademsk1** [comment]
Could the same be done for the Radio component?
