### ISSUE TITLE
[Slider] Add mention that `onMouseDown`/`onMouseUp` aren't functional

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/website#469]
Suggest `onPointerDown`/`onPointerUp` instead.

> Hi @benoitgrelard, maybe worth mentioning in the doc? I think onMouseDown and onMouseUp are pretty commonly used events.

_Originally posted by @Bailig in https://github.com/radix-ui/primitives/issues/1640#issuecomment-1238047368_

**Comment by ItzaMi** [comment]
@benoitgrelard , is this something that I could work on? Would adding a `Caveats` section with this info be enough?

**Comment by benoitgrelard** [comment]
Happy for you to kickstart a PR and we can go from there!

**Comment by abyadando** [comment]
@benoitgrelard I can see it's still issue is still open, so I've decided to take care of it.
