### ISSUE TITLE
Dropdown menu nested menu overflow on mobile

### ISSUE THREAD

**Issue by hichemfantar** [radix-ui/website#553]
### Current Behavior
![Screenshot_20221226-213832.jpg](https://user-images.githubusercontent.com/34947993/209582267-e72822aa-81d6-4767-99a8-8ca805ecba86.jpg)

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |         |         |
| React            | n/a     |         |
| Browser          |  Chrome       |  108.0.5359.128       |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |  Android       |     11    |

**Comment by andy-hook** [comment]
Thanks for raising @hichemfantar , though I feel [this open discussion](https://github.com/radix-ui/primitives/issues/1749) in the primitives repo covers the same concern so will close this in favour.
