### ISSUE TITLE
Improve explanation of `NavigationMenu` `data-motion` in docs

### ISSUE THREAD

**Issue by mluksch** [radix-ui/website#558]
### Relevant Radix Component(s)

Navigation-Menu > Content > data-motion-attributes:
[data-motion-attribute](https://www.radix-ui.com/docs/primitives/components/navigation-menu#content)

I dont understand the meaning of data-motion-attributes in order to trigger the right animation.
Would be great to have better explanations what user action with the nav-menu will result in which data-motion-attribute.

Thank you

**Comment by benoitgrelard** [comment]
The main demo at the top has a full example of this.
