### ISSUE TITLE
Tooltip demo not working

### ISSUE THREAD

**Issue by hey-stefan** [radix-ui/website#562]
### Relevant Radix Component(s)

**Tooltip**
Demo page for the Tooltip does not seem to work. Nothing happens when hovering the "+" icon (macOS Safari 16.1).

**Comment by andy-hook** [comment]
@hey-stefan Does your window have focus? can you provide a video?

**Comment by hey-stefan** [comment]
Well this is embarrassing, but upon further inspection the Tooltip does work. I just did not hold the cursor over it for long enough.

(sidenote: maybe the default delay should be shorter 😅)
