### ISSUE TITLE
Wrong React import in code examples

### ISSUE THREAD

**Issue by tomek-ch** [radix-ui/website#572]
### Relevant Radix Component(s)

The React import is wrong in the code examples on the [getting started page](https://www.radix-ui.com/docs/primitives/overview/getting-started). It should be `'react'`, not `'React'`.

I could make a PR to fix it on this page but it would probably be best to check the whole project for this mistake.

Also, is the import even necessary? Back in the day we needed to import React for JSX to work, but in modern projects it should't be an issue I think? If I paste the code in a `.jsx` or `.tsx` file, the editor complains about an unused variable.

**Comment by andy-hook** [comment]
If you have time to run a quick find and replace for erroneous imports we'd certainly appreciate it.

> Also, is the import even necessary?

It's environment specific really and I don't see the harm in keeping them, they can always be omitted later if not needed.

**Comment by tomek-ch** [comment]
> If you have time to run a quick find and replace for erroneous imports we'd certainly appreciate it.
Sure, I'll fork the repo and submit a PR
> It's environment specific really and I don't see the harm in keeping them, they can always be omitted by the consumer if not needed.
Yeah, makes sense
