### ISSUE TITLE
Styling issue on the code-block dropdown menu 

### ISSUE THREAD

**Issue by ashrafchowdury** [radix-ui/website#620]
## Bug report

On the **ode-block dropdown menu**, there is a styling issue specifically on the dark theme. The dropdown items were not visible unless I gave a hover effect over the field.

### Current Behavior
![image](https://user-images.githubusercontent.com/87828904/228767613-dcb887b2-1ee0-41f6-840e-06fcd077b46d.png)

### Expected behaviour

It should be visible without a hover effect over the field.

**Comment by ashrafchowdury** [comment]
I can fix this issue, can someone please assign me to work on this issue?

**Comment by andy-hook** [comment]
@ashrafchowdury Which OS and browser is this? feel free to raise a PR!

**Comment by ashrafchowdury** [comment]
Yes, this is on **Windows**.

**Comment by ashrafchowdury** [comment]
I've been trying to open the dev server, but I keep running into this **issue**. 👇

Can you please help me to run the local server?

![image](https://user-images.githubusercontent.com/87828904/229154983-a3060a86-ddd5-4c2e-a103-94c8bd3644bf.png)
