### ISSUE TITLE
Components like select, dropdown, causes layout shift on header

### ISSUE THREAD

**Issue by Sls0n** [radix-ui/website#706]
### Current Behavior
The website header layout is shifting when the scrollbar is hidden by scroll lock.

https://github.com/radix-ui/website/assets/102340248/75418526-f247-4f09-8091-9ebfb6b6b06c

### Expected behavior
The website header layout should remain stable when the scrollbar is hidden to prevent layout shift.

### Reproducible example

To reproduce, go to [link](https://www.radix-ui.com/primitives/docs/components/select) and click on select component. This also applies to other scroll locking components like dropdowns, dialogs, etc.

### Suggested solution
Only workaround I could find is to set the width of the header to 100vw, which includes the width of the scrollbar, and then subtract the width of the scrollbar (eg: 17px) using `width: calc(100vw - 17px)`. This makes the header stable, video using the solution ->

https://github.com/radix-ui/website/assets/102340248/6ca83074-847c-456a-a92f-7714bf883a82

### Additional context

None

### Your environment

Brave browser
Windows-10

**Comment by Sls0n** [comment]
Let me know if the suggested solution is acceptable.I can open a pull request immediately if it is.

**Comment by benoitgrelard** [comment]
Hey @Sls0n, thanks for reporting the issue, I've raised a fix.
