### ISSUE TITLE
Update Visual Style Page to show `Basic Usage` 

### ISSUE THREAD

**Issue by 5starkarma** [radix-ui/website#716]
### Overview

There is no `Basic Usage` section on the [Visual Style page](https://www.radix-ui.com/themes/docs/theme/visual-style) which is slightly confusing if you come to that page without reading the docs in order.

### Examples in other libraries or sites

The Dark Mode page has a `Basic Usage` section which makes sense - yet the Visual Style page does not.

![image](https://github.com/radix-ui/website/assets/43155348/aaaa11c3-5db6-4c61-b2ae-213d0ccd0ba2)

### Who does this impact? Who is this for?

All Users

**Comment by benoitgrelard** [comment]
Thanks for taking the time to create an issue. In this case, I don't think each section needs a "Basic Usage" example, so I will close this.
