### ISSUE TITLE
Scroll position in mininav is reset in some situation

### ISSUE THREAD

**Issue by benoitgrelard** [radix-ui/website#72]
This was reported on Discord, but I can't seem to be able to reproduce it myself so not sure if it's specific to some browser or something else.

![](https://cdn.discordapp.com/attachments/759018480334012438/788867665011146752/radixDoc.gif)

**Comment by chaance** [comment]
Hmm interesting. Looks to be Windows Specific from the screenshot. I'm going to copy all of our issue templates from Primitives over here so folks can directly report these issues to us with their specs.

**Comment by benoitgrelard** [comment]
I have tried to reproduce this on Windows via CrossBrowserTesting and I cannot reproduce it.
