### ISSUE TITLE
Broken aria link for radio group

### ISSUE THREAD

**Issue by aldebout** [radix-ui/website#780]
## Documentation

`https://www.w3.org/WAI/ARIA/apg/patterns/radiobutton` looks like it's now `https://www.w3.org/WAI/ARIA/apg/patterns/radio`.
I'd open a PR but I'm not sure what the rules are with the different version mdx files :)

### Relevant Radix Component(s)

Radio Group

### Examples from other doc sites

N/A

**Comment by luke-brobbin-quorum** [comment]
#779 Looks to address this

**Comment by aldebout** [comment]
Fixed by https://github.com/radix-ui/website/pull/795
