### ISSUE TITLE
Discord link is broken

### ISSUE THREAD

**Issue by onursagir** [radix-ui/website#792]
## Bug report
The Discord link in the community section is broken

### Reproducible example

Go to [blog](https://www.radix-ui.com/blog) and press [Discord](https://discord.com/invite/7Xb99uG)

**Comment by vladmoroz** [comment]
Seems fine for me, what do you see?

<img width="762" alt="image" src="https://github.com/radix-ui/website/assets/8441036/78496fe9-a821-4fc4-b9b4-f70caae875df">

**Comment by onursagir** [comment]
@vladmoroz 

<img width="524" alt="image" src="https://github.com/radix-ui/website/assets/2290276/baf62651-d4ba-4c4d-a8f1-bf42ac254d4f">


however it seems to be an issue related to Brave, tried to join it for weeks now 🥹

**Comment by onursagir** [comment]
Yup works there joining as we speak
