### ISSUE TITLE
Zero-dependency larger icon set

### ISSUE THREAD

**Issue by samuelneff** [radix-ui/website#800]
## Documentation

Would there be interest in linking the docs to a larger icon set that has zero dependencies?

### Relevant Radix Component(s)

icons

### Examples from other doc sites

I love Radix UI but found the icon set to be too small for my needs. There are just over 300 icons whereas Material-UI has over 2,000 unique ones (10,000 if you count the 5 styles of each). The Material UI icons have a dependency on Material UI code though so bringing in the icons alone was not feasible.

I created a repackaged version of the icons with zero dependencies. So I can use them with Radix UI without bringing in any Material UI code.

Since the icon set is so much larger, would there be any interest in providing a link to this alternative within the Radix UI documentation? 

https://no-mui-icons.com/

https://www.npmjs.com/search?q=no-mui-icons

https://github.com/samuelneff/no-mui-icons

Thanks,

Sam

**Comment by chaance** [comment]
I think we prefer to keep the scope of the docs to Radix for now. There are tons of icon libraries and this would just be far more documentation we'd need to maintain.
